apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecar-injector-webhook-configmap
data:
  sidecarconfig.yaml: |
    containers:
      - name: sideca<<<<<<< HEADr-nginx
        image: nginx:1.12.2
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
        volumeMounts:
          - name: nginx-conf
            mountPath: /etc/nginx
    volumes:
      - name: testGridLogMount
        hostPath:
          path: /var/log/<<DEPNAME>>
    volumeMounts:
      - name: testGridLogMount
        mountPath: /var/log/
        subPathExpr: $(podname)
    env:
    - name: nodename
      valueFrom:
        fieldRef: {fieldPath: spec.nodeName}
    - name: podname
      valueFrom:
        fieldRef: {fieldPath: metadata.name}
    - name: podnamespace
      valueFrom:
        fieldRef: {fieldPath: metadata.namespace}
    - name: podip
      valueFrom:
        fieldRef: {fieldPath: status.podIP}

