apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecar-injector-webhook-configmap
data:
  sidecarconfig.yaml: |
    containers:
      - name: sidecar-nginx
        image: nginx:1.12.2
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: testGridLogMount
            mountPath: /var/log/default
    volumes:
      - name: testGridLogMount
        hostPath:
          path: /var/log/default
    volumeMounts:
      - name: testGridLogMount
        mountPath: /var/log/
        subPathExpr: $(podname)
    env:
    - name: nodename
      valueFrom:
        fieldRef: {fieldPath: spec.nodeName}
    - name: podname
      valueFrom:
        fieldRef: {fieldPath: metadata.name}
    - name: podnamespace
      valueFrom:
        fieldRef: {fieldPath: metadata.namespace}
    - name: podip
      valueFrom:
        fieldRef: {fieldPath: status.podIP}

