apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecar-injector-webhook-configmap
data:
  sidecarconfig.yaml: |
    initcontainers:
      - name: init-logstash-plugins-install
        image: docker.elastic.co/logstash/logstash:7.2.0
        command:
          - /bin/bash
          - "-c"
          - |
            set -e
            ./bin/logstash-plugin install logstash-codec-multiline logstash-filter-grok
        volumeMounts:
          - name: shared-plugins-logstash
            mountPath: /usr/share/logstash/plugins/
    containers:
      - name: logstash-sidecar
        image: docker.elastic.co/logstash/logstash:7.2.0
        volumeMounts:
          - name: shared-plugins-logstash
            mountPath: /usr/share/logstash/plugins/
          - name: logstash-yaml
            mountPath: /usr/share/logstash/config/logstash.yaml
            subPath: logstash.yaml
          - name: logstash-conf
            mountPath: /usr/share/logstash/pipeline/logstash.conf
            subPath: logstash.conf
        env:
          - name: nodename
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: podname
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: podnamespace
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: podip
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
    volumes:
      - name: shared-plugins-logstash
        emptyDir: {}
      - name: logstash-yaml
        configMap:
          name: logstash-yaml
      - name: logstash-conf
        configMap:
          name: logstash-conf
    env:
      - name: nodename
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: podname
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: podnamespace
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: podip
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
